version: '3.8'

services:
  email_scraper_api:
    build:
        context: ./app
        dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
  email_scraper_worker:
    build:
        context: ./worker
        dockerfile: Dockerfile
    command: python worker.py
    volumes:
      - ./worker:/usr/src/worker
    depends_on:
      - redis

volumes:
  redis_data: